### ISSUE TITLE
Possibillity to send Kodi machine to sleep

### ISSUE THREAD

**Issue by popanz** [Julien-Blanc-tgcm/kontroller#31]
Now, that it is possible to wake my kodi machine it would make sense to add an option to send it to sleep.

**Comment by Julien-Blanc-tgcm** [comment]
It's already possible from the server management page, pulley menu. However, there is only reboot / shutdown options. I'll add suspend / hibernate, but with a settings in the server settings page to individually enable them (otherwise the list in the pulley gets too long), and some don't make any sense with certain hardware (iirc you can't put a raspberry pi into hibernation or suspend mode).

**Comment by Julien-Blanc-tgcm** [comment]
Options added in v0.17
